trailing_whitespace:
  ignores_empty_lines: true
  
vertical_whitespace:
  max_empty_lines: 1
  
line_length:
  warning: 200
  error: 1000
  
type_name:
  min_length: 2
  max_length: 50
  allowed_symbols: ["_"]

function_parameter_count:
  warning: 10
  error: 20

large_tuple:
  warning: 10
  error: 20

identifier_name:
  min_length: 2
