language: objective-c # no matter that it is swift :)
osx_image: xcode11.2
script:
    - xcodebuild -project TweeTextField.xcodeproj -scheme "TweeTextField-Sample" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=10.3.1,name=iPhone 5" -configuration Debug -PBXBuildsContinueAfterErrors=0 ACTIVE_ARCH_ONLY=0 build
    - xcodebuild -project TweeTextField.xcodeproj -scheme "TweeTextField" -sdk iphonesimulator -configuration Debug -PBXBuildsContinueAfterErrors=0 ACTIVE_ARCH_ONLY=0 build
    - pod lib lint --verbose --fail-fast
