name: deploy_to_cocoapods

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - uses: michaelhenry/deploy-to-cocoapods-github-action@1.0.9
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.app
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}