author: Jeff Kelley
author_url: https://jeffkelley.org
github_url: https://github.com/Detroit-Labs/SheetPresentation
root_url: https://detroit-labs.github.io/SheetPresentation/
module: SheetPresentation
